package main

import (
	"errors"
	"io"
	"text/template"
)

const vmxTemplate = `.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "9"
vcpu.hotadd = "TRUE"
scsi0.present = "TRUE"
scsi0.virtualDev = "lsisas1068"
memsize = "4096"
mem.hotadd = "TRUE"
scsi0:0.present = "TRUE"
scsi0:0.fileName = "{{.VMDKFile}}"
ethernet0.present = "TRUE"
ethernet0.connectionType = "nat"
ethernet0.virtualDev = "e1000e"
ethernet0.wakeOnPcktRcv = "FALSE"
ethernet0.addressType = "generated"
ethernet0.linkStatePropagation.enable = "TRUE"
usb.present = "TRUE"
ehci.present = "TRUE"
ehci.pciSlotNumber = "34"
usb_xhci.present = "TRUE"
sound.present = "TRUE"
sound.virtualDev = "hdaudio"
sound.fileName = "-1"
sound.autodetect = "TRUE"
serial0.present = "TRUE"
serial0.fileType = "thinprint"
pciBridge0.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
vmci0.present = "TRUE"
hpet0.present = "TRUE"
tools.syncTime = "TRUE"
displayName = "2012R2-Stemcell-Base"
guestOS = "windows8srv-64"
virtualHW.productCompatibility = "hosted"
keyboardAndMouseProfile = "52179908-6e91-f1e0-34b6-b6065d923f89"
tools.upgrade.policy = "upgradeAtPowerCycle"
powerType.powerOff = "soft"
powerType.powerOn = "soft"
powerType.suspend = "soft"
powerType.reset = "soft"
ehci:0.parent = "-1"
ehci:0.port = "0"
ehci:0.deviceType = "video"
numvcpus = "4"
ide0:0.present = "TRUE"
ide0:0.autodetect = "TRUE"
ide0:0.deviceType = "cdrom-raw"
ide0:0.startConnected = "FALSE"
ide0:0.fileName = "auto detect"
uuid.bios = "56 4d 29 ea 8d 32 f8 f5-0a 9f b9 82 0e 0c 5c 4b"
uuid.location = "56 4d 29 ea 8d 32 f8 f5-0a 9f b9 82 0e 0c 5c 4b"
scsi0:0.redo = ""
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
scsi0.pciSlotNumber = "160"
usb.pciSlotNumber = "32"
ethernet0.pciSlotNumber = "192"
sound.pciSlotNumber = "33"
usb_xhci.pciSlotNumber = "224"
vmci0.pciSlotNumber = "35"
scsi0.sasWWID = "50 05 05 6a 8d 32 f8 f0"
ethernet0.generatedAddress = "00:0c:29:0c:5c:4b"
ethernet0.generatedAddressOffset = "0"
vmci0.id = "1763418186"
monitor.phys_bits_used = "40"
vmotion.checkpointFBSize = "134217728"
cleanShutdown = "TRUE"
softPowerOff = "TRUE"
usb_xhci:1.speed = "2"
usb_xhci:1.present = "TRUE"
usb_xhci:1.deviceType = "hub"
usb_xhci:1.port = "1"
usb_xhci:1.parent = "-1"
usb_xhci:3.speed = "4"
usb_xhci:3.present = "TRUE"
usb_xhci:3.deviceType = "hub"
usb_xhci:3.port = "3"
usb_xhci:3.parent = "-1"
gui.fitGuestUsingNativeDisplayResolution = "TRUE"
tools.remindInstall = "FALSE"
toolsInstallManager.updateCounter = "1"
toolsInstallManager.lastInstallError = "0"
isolation.tools.hgfs.disable = "false"
hgfs.mapRootShare = "true"
hgfs.linkRootShare = "true"
mks.enable3d = "TRUE"
sata0.present = "FALSE"
sata0:1.present = "FALSE"
floppy0.present = "FALSE"
vm.genid = "-1524181149801250576"
vm.genidX = "-4136781299046921680"
checkpoint.vmState = ""
usb_xhci:4.present = "TRUE"
usb_xhci:4.deviceType = "hid"
usb_xhci:4.port = "0"
usb_xhci:4.parent = "1"
`

func VMXTemplate(vmdk string, w io.Writer) error {
	if vmdk == "" {
		return errors.New("vmx template: empty vmdk filename")
	}
	type context struct {
		VMDKFile string
	}
	ctxt := context{VMDKFile: vmdk}
	t, err := template.New("vmx template").Parse(vmxTemplate)
	if err != nil {
		return err
	}
	return t.Execute(w, ctxt)
}
